name: Publish to GitHub

on:
  workflow_run:
    workflows: [Publish To All]
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: ./gradlew publishGithub
